/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rangolibre.view.interfaceprincipal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import org.rangolibre.control.ControleMesa;
import org.rangolibre.model.BotaoMesa;
import org.rangolibre.model.Mesa;

/**
 *
 * @author aleaguado
 */
public class FramePedidoBuscaMesa extends javax.swing.JInternalFrame {
        FramePedidoPrincipal fm = new FramePedidoPrincipal();
    /**
     * Creates new form FramePedidoBuscaMesa
     */
    public FramePedidoBuscaMesa(FramePedidoPrincipal fp) {
        fm = fp;
        this.setSize(fp.getSize());
        initComponents();
        criarBotoes();
    }
    
    public void criarBotoes(){
        
        try {
            ControleMesa controleMesa = new ControleMesa();
            Icon iconeMesa = new ImageIcon(getClass().getResource("/org/rangolibre/img/botoes/24x24/mesa.png"));  
            ArrayList<Mesa> listaMesa = new ArrayList<Mesa>();
            listaMesa = controleMesa.obterMesas();
            //Crio o objeto BotaoMesa com o tamanho necessário
            BotaoMesa[] listaBotaoMesa = new BotaoMesa[listaMesa.size()];
            
            int linhas = (listaMesa.size()/8)+1;
            painelMesas.setLayout(new GridLayout(linhas,8));
            
            
            for (int i = 0; i < listaMesa.size(); i++) {
                listaBotaoMesa[i] = new BotaoMesa( new JButton(listaMesa.get(i).getId()),listaMesa.get(i) ); 
                listaBotaoMesa[i].bt.setIcon(iconeMesa);
                listaBotaoMesa[i].bt.setVerticalTextPosition(SwingConstants.BOTTOM);
                listaBotaoMesa[i].bt.setHorizontalTextPosition(SwingConstants.CENTER);
                painelMesas.add(listaBotaoMesa[i].bt);
                
                if (listaMesa.get(i).getStatus().equals("L")) {
                     listaBotaoMesa[i].bt.setBackground(Color.GREEN);
                } else {
                     listaBotaoMesa[i].bt.setBackground(Color.RED);
                }
                
                
                listaBotaoMesa[i].bt.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        try {
                            ActionPerformed(evt);
                        } catch (PropertyVetoException ex) {
                            Logger.getLogger(FramePedidoBuscaMesa.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
        });
   
            }

        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());    
        }    
    
    }
    
    private void ActionPerformed(java.awt.event.ActionEvent evt) throws PropertyVetoException {
        fm.carregarCampoMesa(evt.getActionCommand().trim());
        this.setClosed(true);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMesas = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Mesas");

        javax.swing.GroupLayout painelMesasLayout = new javax.swing.GroupLayout(painelMesas);
        painelMesas.setLayout(painelMesasLayout);
        painelMesasLayout.setHorizontalGroup(
            painelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        painelMesasLayout.setVerticalGroup(
            painelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelMesas;
    // End of variables declaration//GEN-END:variables
}
