/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rangolibre.view.interfaceprincipal;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.rangolibre.control.ControlePedido;
import org.rangolibre.model.Cliente;
import org.rangolibre.model.Pedido;

/**
 *
 * @author aleaguado
 */
public class FramePedidoAdicionarCliente extends javax.swing.JInternalFrame {
    Pedido pedido;
    FramePedidoPrincipal fm = new FramePedidoPrincipal();
    /**
     * Creates new form FramePedidoAdicionarCliente
     */
    public FramePedidoAdicionarCliente(Pedido ped, FramePedidoPrincipal fp) {
        this.setSize(96,36);
        initComponents();
        btConfirmarAdd.setEnabled(false);
        btCancelarAdd.setEnabled(false);
        pedido = ped;
        fm = fp;
        prepararTela();
    }
    
    private void prepararTela(){
        textoMesaAdd.setText(pedido.getMesa().getId().trim());
        textoMesaAdd.setEnabled(false);
        
        textoPedidoAdd.setText(pedido.getId().trim());
        textoPedidoAdd.setEnabled(false);
        
        textoClienteAdd.setText("");
        textoClienteAdd.requestFocus();
        
        btConfirmarAdd.setEnabled(true);
        btCancelarAdd.setEnabled(true);
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelMesaAdd = new javax.swing.JLabel();
        labelPedidoAdd = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        btConfirmarAdd = new javax.swing.JButton();
        btCancelarAdd = new javax.swing.JButton();
        textoMesaAdd = new javax.swing.JTextField();
        textoPedidoAdd = new javax.swing.JTextField();
        textoClienteAdd = new javax.swing.JTextField();

        setTitle("Adicionar Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelMesaAdd.setText("Mesa:");

        labelPedidoAdd.setText("Pedido:");

        labelCliente.setText("Nome Cliente:");

        btConfirmarAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rangolibre/img/botoes/24x24/001_06.png"))); // NOI18N
        btConfirmarAdd.setText("Salvar");
        btConfirmarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarAddActionPerformed(evt);
            }
        });

        btCancelarAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rangolibre/img/botoes/24x24/001_05.png"))); // NOI18N
        btCancelarAdd.setText("Cancelar");
        btCancelarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarAddActionPerformed(evt);
            }
        });

        textoMesaAdd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textoMesaAdd.setText("jTextField1");

        textoPedidoAdd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textoPedidoAdd.setText("jTextField2");

        textoClienteAdd.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        textoClienteAdd.setText("jTextField3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoClienteAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPedidoAdd)
                                    .addComponent(labelMesaAdd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoMesaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoPedidoAdd)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btConfirmarAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelarAdd)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMesaAdd)
                    .addComponent(textoMesaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPedidoAdd)
                    .addComponent(textoPedidoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente)
                    .addComponent(textoClienteAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmarAdd)
                    .addComponent(btCancelarAdd))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarAddActionPerformed
             if ( JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar as ações?") == 0) {
                 try {
                     this.setClosed(true);
                 } catch (PropertyVetoException ex) {
                     Logger.getLogger(FramePedidoAdicionarCliente.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_btCancelarAddActionPerformed

    private void btConfirmarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarAddActionPerformed
        if (textoClienteAdd.getText().trim().length() < 1)
            return;
        
        if ( JOptionPane.showConfirmDialog(null, "Deseja realmente criar o cliente " + textoClienteAdd.getText() + " ?") == 0) {
                 try {
                     ControlePedido controlePedido = new ControlePedido();
                     Cliente cliente = new Cliente();
                     cliente.setPedido(pedido);
                     cliente.setNomeCliente(textoClienteAdd.getText().trim());
                     
                     controlePedido.criarCliente(cliente);
                     fm.decisaoComMesa(pedido.getMesa());
                     fm.setarComboCliente(cliente.getNomeCliente());
                     this.setClosed(true);
                          
                    } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                            }
             }       
        
// TODO add your handling code here:
    }//GEN-LAST:event_btConfirmarAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarAdd;
    private javax.swing.JButton btConfirmarAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelMesaAdd;
    private javax.swing.JLabel labelPedidoAdd;
    private javax.swing.JTextField textoClienteAdd;
    private javax.swing.JTextField textoMesaAdd;
    private javax.swing.JTextField textoPedidoAdd;
    // End of variables declaration//GEN-END:variables
}
