/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rangolibre.view.interfaceprincipal;

import java.awt.Component;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.rangolibre.control.ControleCardapio;
import org.rangolibre.control.ControleIngrediente;
import org.rangolibre.model.CatIngre;
import org.rangolibre.model.Ingrediente;
import org.rangolibre.model.IngredienteCardapio;
import org.rangolibre.model.ItemCard;

/**
 *
 * @author aleaguado
 */
public class FramePedidoExplodir extends javax.swing.JInternalFrame {
    FramePedidoPrincipal fm;
    ArrayList<Ingrediente> listaIngredienteTotal;
    ArrayList<IngredienteCardapio> listaIngredienteSelecionada;
    ItemCard padrao;
    ControleCardapio controleCardapio = new ControleCardapio();
    ControleIngrediente controleIngrediente = new ControleIngrediente();
    ArrayList<CatIngre> listaCategorias;
    IngredienteCardapio selected;
    DefaultListModel modeloSelecionada = new DefaultListModel();
    DefaultListModel modeloTotal = new DefaultListModel();
    String pontoCarne;
    /**
     * Creates new form FramePedidoExplodir
     */
    public FramePedidoExplodir(ItemCard referencia, FramePedidoPrincipal fp) {

        initComponents(); 
        
        fm = fp;
        try {
        if (referencia.getPadrao())
            padrao = referencia;
        else
            padrao = controleCardapio.obterItemPadrao(referencia);
        
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }
        
        carregarCampos();
        
    }
    
    private void carregarCampos(){
        textoItemPadrao.setText(padrao.getDescCard());
        textoItemNovo.setText(padrao.getDescCard());
        textoItemPadrao.setEnabled(false);
        textoItemNovo.setEnabled(true);
        
        listaIngredientesContidos.setModel(modeloSelecionada);
        listaIngredientesDisponiveis.setModel(modeloTotal);

        comboCategoriaIngredientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
            if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                categoriaIngredientesActionPerformed();
        }
   } 

        });
        
        carregarListaIngredientesSelecionados();
        carregarComboCategoria();
    
    }
    
    private void carregarComboCategoria(){
        
        try {
            comboCategoriaIngredientes.setEnabled(true);
            comboCategoriaIngredientes.removeAllItems();
            listaCategorias = controleIngrediente.obterListaCategoria();
    
            comboCategoriaIngredientes.addItem("TODOS");
            
            for (int i = 0; i < listaCategorias.size(); i++) {
                comboCategoriaIngredientes.addItem(listaCategorias.get(i).getDesc());
            }
            
            comboCategoriaIngredientes.setSelectedIndex(0);
             
   } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }
    }

    private void comporDescricao(ItemCard novoItem){

        textoItemNovo.setEnabled(true);
        textoItemNovo.setText(controleCardapio.comporDescricaoDerivada(novoItem, padrao));
        textoItemNovo.setEnabled(false);    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        labelPadrao = new javax.swing.JLabel();
        labelNovo = new javax.swing.JLabel();
        textoItemPadrao = new javax.swing.JTextField();
        textoItemNovo = new javax.swing.JTextField();
        painelEsquerdo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textoQuantidade = new javax.swing.JTextField();
        btAlterarQty = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaIngredientesContidos = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        textoCarne = new javax.swing.JTextField();
        painelDireito = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaIngredientesDisponiveis = new javax.swing.JList();
        painelBotoesCentral = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboCategoriaIngredientes = new javax.swing.JComboBox();

        setClosable(true);

        painelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelPadrao.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelPadrao.setText("Item Padrão:");

        labelNovo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelNovo.setText("Novo Item:");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPadrao)
                    .addComponent(labelNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoItemPadrao)
                    .addComponent(textoItemNovo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPadrao)
                    .addComponent(textoItemPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNovo)
                    .addComponent(textoItemNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelEsquerdo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingredientes contidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel2.setText("Quantidade:");

        textoQuantidade.setToolTipText("");

        btAlterarQty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rangolibre/img/botoes/24x24/001_06.png"))); // NOI18N
        btAlterarQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarQtyActionPerformed(evt);
            }
        });

        listaIngredientesContidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaIngredientesContidosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaIngredientesContidos);

        jLabel3.setText("*Ponto da Carne:");

        javax.swing.GroupLayout painelEsquerdoLayout = new javax.swing.GroupLayout(painelEsquerdo);
        painelEsquerdo.setLayout(painelEsquerdoLayout);
        painelEsquerdoLayout.setHorizontalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(3, 3, 3)
                                .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAlterarQty))
                            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelEsquerdoLayout.setVerticalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btAlterarQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelDireito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingredientes Disponíveis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jScrollPane4.setViewportView(listaIngredientesDisponiveis);

        javax.swing.GroupLayout painelDireitoLayout = new javax.swing.GroupLayout(painelDireito);
        painelDireito.setLayout(painelDireitoLayout);
        painelDireitoLayout.setHorizontalGroup(
            painelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDireitoLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelDireitoLayout.setVerticalGroup(
            painelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDireitoLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        painelBotoesCentral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rangolibre/img/botoes/24x24/001_23_1.png"))); // NOI18N
        btAdicionar.setToolTipText("Adicionar ingrediente");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        botaoRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rangolibre/img/botoes/24x24/001_21.png"))); // NOI18N
        botaoRemover.setToolTipText("Remover Ingrediente");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesCentralLayout = new javax.swing.GroupLayout(painelBotoesCentral);
        painelBotoesCentral.setLayout(painelBotoesCentralLayout);
        painelBotoesCentralLayout.setHorizontalGroup(
            painelBotoesCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAdicionar)
                    .addComponent(botaoRemover))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        painelBotoesCentralLayout.setVerticalGroup(
            painelBotoesCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesCentralLayout.createSequentialGroup()
                .addComponent(btAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoRemover)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rangolibre/img/botoes/24x24/001_06.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rangolibre/img/botoes/24x24/001_05.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Categoria:");

        comboCategoriaIngredientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCategoriaIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaIngredientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(painelBotoesCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCategoriaIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelDireito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addGap(37, 37, 37)
                .addComponent(btCancelar)
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboCategoriaIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelDireito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(painelBotoesCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed

       try { 
            if (modeloSelecionada.contains(listaIngredientesDisponiveis.getSelectedValue())){
                JOptionPane.showMessageDialog(null, "Ingrediente já adicionado!!!");
                return;
            }

           int indexC;
           indexC = listaIngredientesDisponiveis.getSelectedIndex();
           Ingrediente ingre = listaIngredienteTotal.get(indexC);
           IngredienteCardapio ingreCard = new IngredienteCardapio(1,ingre);
           listaIngredienteSelecionada.add(ingreCard);
           modeloSelecionada.addElement(ingreCard.getIngrediente().getDesc());
           
           textoItemNovo.setText(textoItemNovo.getText() + " C/ " + ingreCard.getIngrediente().getDesc().substring(0, 5) + ";" );
           
           //Atualiza o combolist dos selecionados
           //carregarListaIngredientesSelecionadosPos();

           //Atualiza o combolist dos disponíveis
           //carregarListaIngredientesDisponiveis();

           //Marcamos o item novo como selecionado.
           listaIngredientesContidos.setSelectedIndex(listaIngredientesContidos.getLastVisibleIndex());
           
   } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }
       
       
// TODO add your handling code here:
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        try {
            int indexC;
           indexC = listaIngredientesContidos.getSelectedIndex();

           selected = listaIngredienteSelecionada.get(indexC);

           listaIngredienteSelecionada.remove(selected);

           //Atualiza o combolist dos selecionados
           //carregarListaIngredientesSelecionadosPos();
           modeloSelecionada.remove(indexC);
           
           textoItemNovo.setText(textoItemNovo.getText() + " S/ " + selected.getIngrediente().getDesc().substring(0, 5) + ";" );
           
           //Atualiza o combolist dos disponíveis
           //carregarListaIngredientesDisponiveis();      
     } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }     
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void comboCategoriaIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaIngredientesActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriaIngredientesActionPerformed

    private void btAlterarQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarQtyActionPerformed
        try {
            selected.setQty(Integer.parseInt(textoQuantidade.getText()));
            JOptionPane.showMessageDialog(null, "Quantidade Atualizada!!!");
       } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }    
        
// TODO add your handling code here:
    }//GEN-LAST:event_btAlterarQtyActionPerformed

    private void listaIngredientesContidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaIngredientesContidosValueChanged
      try{
       int indexC;
       indexC = listaIngredientesContidos.getSelectedIndex();
       
       if (indexC < 0) //Teste para volta da exclusão
           return;

       selected = listaIngredienteSelecionada.get(indexC);
       
       textoQuantidade.setEnabled(true);
       textoQuantidade.setText(Integer.toString(selected.getQty()));
      
   } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }

// TODO add your handling code here:
    }//GEN-LAST:event_listaIngredientesContidosValueChanged

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
 
        try {
            this.setClosed(true);
            
    } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
 
        try {
            pontoCarne = textoCarne.getText().trim();
            ItemCard novoItem = new ItemCard();
            novoItem.setAtivo("Y");
            novoItem.setDescCard("");
            novoItem.setDescCat(padrao.getDescCat());
            //novoItem.setIdCard();
            novoItem.setIngre(listaIngredienteSelecionada);
            novoItem.setPadrao(false);
            novoItem.setPonto(pontoCarne);
            novoItem.setTipo(padrao.getTipo());
            novoItem.setUsr(fm.p.usuario);
            novoItem.setpreco(padrao.getpreco());
            novoItem.setIdCat(padrao.getIdCat());

        //comporDescricao(novoItem);
        
        novoItem.setDescCard(textoItemNovo.getText().trim() + textoCarne.getText().trim());
        
        controleCardapio.criarDerivado(novoItem, padrao);
        
        JOptionPane.showMessageDialog(null, "Item Criado!!!");
        
        fm.carregarPainelPadrao(novoItem.getTipo());
        
        this.setClosed(true);
        
    } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }       
        

// TODO add your handling code here:
    }//GEN-LAST:event_btSalvarActionPerformed

    private void carregarListaIngredientesDisponiveis(){
        int i = 0;
   try {

       modeloTotal.clear();
       if (comboCategoriaIngredientes.getSelectedIndex() == 0) {
            listaIngredienteTotal = controleIngrediente.obterListaIngrediente(99999);

       } else {     
                while(!listaCategorias.get(i).getDesc().equals(comboCategoriaIngredientes.getSelectedItem().toString().trim())) {
                    i++;
                }
                listaIngredienteTotal = controleIngrediente.obterListaIngrediente(listaCategorias.get(i).getId());

       }

        for (int j = 0; j < listaIngredienteTotal.size(); j++) {
            
           // if (!modeloSelecionada.contains(listaIngredienteTotal.get(j).getDesc())) {
             modeloTotal.add(j, listaIngredienteTotal.get(j).getDesc());
           // }
        }
    
   } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }
   
    }
       
    private void categoriaIngredientesActionPerformed(){    
        
        carregarListaIngredientesDisponiveis();
    }
    
    private void carregarListaIngredientesSelecionados(){
        try {
            
        modeloSelecionada.clear();
        
        
       
        padrao.setIngre(controleCardapio.obterListaIngrediente(padrao.getIdCard()));
        
        listaIngredienteSelecionada = controleCardapio.obterListaIngrediente(padrao.getIdCard());
        
        for (int j = 0; j < listaIngredienteSelecionada.size(); j++) {
            modeloSelecionada.add(j, listaIngredienteSelecionada.get(j).getIngrediente().getDesc());
        }      
           } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }    
    }
    
    private void carregarListaIngredientesSelecionadosPos(){
        try {
        
        modeloSelecionada.clear();    
        for (int j = 0; j < listaIngredienteSelecionada.size(); j++) {
            modeloSelecionada.add(j, listaIngredienteSelecionada.get(j).getIngrediente().getDesc());
        }

           } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());  
                }    
    }    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterarQty;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    public javax.swing.JComboBox comboCategoriaIngredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelNovo;
    private javax.swing.JLabel labelPadrao;
    private javax.swing.JList listaIngredientesContidos;
    private javax.swing.JList listaIngredientesDisponiveis;
    private javax.swing.JPanel painelBotoesCentral;
    private javax.swing.JPanel painelDireito;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JTextField textoCarne;
    private javax.swing.JTextField textoItemNovo;
    private javax.swing.JTextField textoItemPadrao;
    private javax.swing.JTextField textoQuantidade;
    // End of variables declaration//GEN-END:variables
}
